/// <reference types="astro/client" />

import type { ResolvedConfig } from '@atomic-platform/shared-types';

// The global `Env` interface is generated by `wrangler types` into
// worker-configuration.d.ts at the package root. `App.Locals.site` is
// populated by src/middleware.ts from KV on every request.

declare global {
  namespace App {
    interface Locals {
      site: {
        siteId: string;
        hostname: string;
        config: ResolvedConfig;
        /** True when the request was resolved via `?_atl_site=` preview
         *  override. Preview mode bypasses article-status filtering so
         *  review/draft articles are visible for content review. */
        isPreview: boolean;
        /** True when served from workers.dev or localhost — ad scripts
         *  and interstitials are suppressed to avoid burning real
         *  impressions on staging/preview environments. */
        isStaging: boolean;
      };
    }
  }
}

export {};
