/// <reference types="astro/client" />

import type { ResolvedConfig } from '@atomic-platform/shared-types';

// The global `Env` interface is generated by `wrangler types` into
// worker-configuration.d.ts at the package root. `App.Locals.site` is
// populated by src/middleware.ts from KV on every request.

declare global {
  namespace App {
    interface Locals {
      site: {
        siteId: string;
        hostname: string;
        config: ResolvedConfig;
      };
    }
  }
}

export {};
