import TurndownService from "turndown";

/**
 * Convert WordPress HTML content to clean Markdown.
 *
 * Pre-processes WP shortcodes, Elementor/wp-block wrapper divs,
 * then converts via Turndown with custom rules to strip images,
 * iframes, and figcaptions.
 */
export function wpHtmlToMarkdown(html: string): string {
  if (!html || !html.trim()) {
    return "";
  }

  // --- Pre-process ---

  // Strip paired WP shortcodes first: [caption ...]...[/caption]
  let cleaned = html.replace(
    /\[([\w_-]+)(?:\s[^\]]*)?][\s\S]*?\[\/\1]/g,
    "",
  );
  // Strip remaining self-closing shortcodes: [gallery ids="1,2,3"]
  cleaned = cleaned.replace(/\[[\w_-]+(?:\s[^\]]*)?]/g, "");

  // Strip Elementor wrapper divs (keep inner content)
  cleaned = cleaned.replace(
    /<div\s+class="[^"]*elementor[^"]*"[^>]*>([\s\S]*?)<\/div>/gi,
    "$1",
  );

  // Strip wp-block wrapper divs (keep inner content)
  cleaned = cleaned.replace(
    /<div\s+class="[^"]*wp-block[^"]*"[^>]*>([\s\S]*?)<\/div>/gi,
    "$1",
  );

  // --- Turndown ---

  const turndown = new TurndownService({
    headingStyle: "atx",
    codeBlockStyle: "fenced",
    bulletListMarker: "-",
  });

  // Remove img tags (hero images are regenerated by Gemini)
  turndown.addRule("removeImages", {
    filter: "img",
    replacement: () => "",
  });

  // Remove iframe tags
  turndown.addRule("removeIframes", {
    filter: "iframe",
    replacement: () => "",
  });

  // Remove figcaption tags
  turndown.addRule("removeFigcaptions", {
    filter: "figcaption",
    replacement: () => "",
  });

  const markdown = turndown.turndown(cleaned);

  // --- Post-process ---

  // Collapse excessive newlines and trim
  return markdown.replace(/\n{3,}/g, "\n\n").trim();
}
